### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ernara** [mbalchanowski/Ant-Colony-System#1]
Ant-Colony-System-master\TSP\kroA100.tsp" because it was not found.	

AntColonySystem C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4950

**Comment by mbalchanowski** [comment]
Hello **Ernara**,

as I stated in readme file, you have to: 
_"Create TSP directory inside project folder and put there some .tsp file from TSPLIB repository.
By default it tries to load kroA100.tsp file. You can change load path in Program.cs file."_
